version: '2'

services:
  db:
    hostname: db
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - fabrik-pro

  reactjs:
    container_name: reactjs
    hostname: reactjs
    build:
      context: ./
      dockerfile: docker/dev/reactjs/Dockerfile
    environment:
      NODE_ENV: development
    volumes:
      - .:/code
      - /code/node_modules
    networks:
      - fabrik-pro

  django:
    restart: always
    container_name: django
    hostname: django
    env_file:
      - docker/dev.env
    links:
      - reactjs
    build:
      context: ./
      dockerfile: docker/dev/django/Dockerfile
    ports:
      - "8000:8000"
    command: ["./docker/wait-for-it.sh", "db:5432", "--", "sh", "/code/docker/dev/django/container-start.sh"]
    depends_on:
      - db
      - reactjs
    volumes:
      - .:/code
    networks:
      - fabrik-pro

networks:
  fabrik-pro:
